### ISSUE TITLE
Deep Reinforcement Learning  Documentation hyperlink issue

### ISSUE THREAD

**Issue by Raynhardt-Van-Zyl** [rl-tools/rl-tools#12]
The readme "Documentation" chapter has a hyperlink issue.

is: 
https://docs.rl.tools/06-Deep%20Reinforcement%20Lear
should be:
https://docs.rl.tools/06-Deep%20Reinforcement%20Learning.html

**Comment by jonas-eschmann** [comment]
Hi @Raynhardt-Van-Zyl 

sorry, I forgot to answer. Thank you for pointing it out! I fixed it now
